name: Linting

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  code_quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: selene,typos-cli,stylua
      - name: Run linters
        run: |
          make lint

  code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: JohnnyMorganz/stylua-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check --glob '!lua/neogit/lib/vendor/**' --glob '**/*.lua' lua tests

  ruby_lint:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rubocop

  lua_types:
    name: lua-typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install lua-language-server
        run: |
          sudo mkdir -p /usr/local/lua-language-server
          sudo chown "$(id -u)" /usr/local/lua-language-server
          curl -sL "https://github.com/LuaLS/lua-language-server/releases/download/3.13.6/lua-language-server-3.13.6-linux-x64.tar.gz" \
            | tar xz -C /usr/local/lua-language-server
          sudo ln -sf /usr/local/lua-language-server/bin/lua-language-server /usr/local/bin/lua-language-server
          lua-language-server --version

      - uses: luarocks/gh-actions-lua@v10
        with:
          luaVersion: luajit
      - uses: luarocks/gh-actions-luarocks@v5
        with:
          luaRocksVersion: "3.12.1"
      - run: |
         luarocks install llscheck
         llscheck --checklevel Warning lua/
